name: sanjeevani
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: 2.5.3
  flutter_map: ^8.2.2
  location: ^8.0.1
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_dotenv: ^6.0.0
  web_socket_channel: ^3.0.3
  provider: ^6.1.5+1
  google_ml_kit: ^0.21.0
  record: ^6.2.0
  audioplayers: ^6.5.1
  google_mlkit_text_recognition: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/images/
    - .env
